/*
  Downloads the web fonts from Google Fonts and rewrites them to be served
  from /fonts on our own origin. We keep the unicode-range blocks that Google
  generates, which is what makes the browser fetch only the Armenian subset
  when it meets Armenian text and only the Latin subset otherwise. That is
  the subsetting the brief asks for, done by the people who maintain the font.

  Run this once. The output is committed. It is not part of the build.
*/
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const FAMILIES = [
  "Noto+Sans+Armenian:wght@400;500;600;700",
  "Noto+Serif+Armenian:wght@500;600;700",
];
const URL_CSS = `https://fonts.googleapis.com/css2?${FAMILIES.map(
  (f) => `family=${f}`,
).join("&")}&display=swap`;

// Google serves woff2 only to browsers that advertise support for it.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const OUT_DIR = join(process.cwd(), "public", "fonts");
const CSS_OUT = join(process.cwd(), "src", "styles", "fonts.css");

const res = await fetch(URL_CSS, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
let css = await res.text();

await mkdir(OUT_DIR, { recursive: true });

const urls = [...new Set([...css.matchAll(/url\((https:[^)]+)\)/g)].map((m) => m[1]))];
console.log(`Found ${urls.length} font files.`);

let downloaded = 0;
for (const url of urls) {
  // https://fonts.gstatic.com/s/notosansarmenian/v43/<hash>.woff2
  const parts = url.split("/");
  const family = parts[parts.length - 3];
  const file = `${family}-${parts[parts.length - 1]}`;
  const bin = await fetch(url, { headers: { "User-Agent": UA } });
  if (!bin.ok) throw new Error(`${url} returned ${bin.status}`);
  await writeFile(join(OUT_DIR, file), Buffer.from(await bin.arrayBuffer()));
  css = css.split(url).join(`/fonts/${file}`);
  downloaded += 1;
}

const header = `/*
  Self hosted web fonts. Generated by scripts/fetch-fonts.mjs, then committed.
  Do not edit by hand. Re run the script to update.

  Both families cover Armenian and Latin so a bilingual line does not swap
  fonts mid sentence. The unicode-range blocks below mean a visitor reading
  English never downloads the Armenian glyphs.
*/\n\n`;

await writeFile(CSS_OUT, header + css.trim() + "\n");
console.log(`Wrote ${downloaded} files to public/fonts and src/styles/fonts.css`);
