/*
  Subsets the Armenian faces to the characters this site actually uses.

  WHY

  Google serves Noto Sans Armenian and Noto Serif Armenian split by
  unicode-range, so an English reader never downloads the Armenian block.
  That is the right design and it is why the fonts were self hosted this way.

  It does not help here, because the wordmark in the header says Գաթա on every
  page. Three characters. Those three pull the whole Armenian subset, 26.2 KB
  of the sans and 33.8 KB of the serif, onto all seventeen pages, including the
  label page somebody scans on cellular in a kitchen while worried about an
  allergy.

  So the Armenian faces are cut down to the codepoints that appear in the
  source. Three glyphs come to roughly one kilobyte instead of sixty.

  SAFETY

  Subsetting is a trap if the text later changes: a new Armenian word renders
  in a fallback font, or as boxes, and nothing says so. Two things prevent
  that. This script derives the codepoint list from the source rather than
  taking a hardcoded list, so re-running it after adding copy is enough. And
  scripts/check-html.mjs fails the build if the generated HTML contains an
  Armenian character that is not in the subset.

  Run: npm run fonts:subset   Output is committed. Not part of the build.
*/

import { readFile, writeFile, readdir, stat } from "node:fs/promises";
import { join, extname, relative } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);
const ROOT = process.cwd();
const FONT_DIR = join(ROOT, "public", "fonts");
const CSS = join(ROOT, "src", "styles", "fonts.css");
const MANIFEST = join(ROOT, "src", "styles", "armenian-subset.json");

/* The Armenian block, plus the ligatures Noto places in the same subset. */
const IS_ARMENIAN = (cp) =>
  (cp >= 0x0530 && cp <= 0x058f) || (cp >= 0xfb13 && cp <= 0xfb17);

const SKIP = new Set(["node_modules", ".git", "dist", ".astro", "public"]);
const SCAN = new Set([".astro", ".ts", ".tsx", ".json", ".md", ".css", ".mjs"]);

async function* walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (SKIP.has(e.name)) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) yield* walk(full);
    else if (SCAN.has(extname(e.name))) yield full;
  }
}

/* ---- 1. Which Armenian characters does the source actually contain? ---- */

const used = new Set();
const seenIn = new Map();

for await (const file of walk(ROOT)) {
  const text = await readFile(file, "utf8");
  for (const ch of text) {
    const cp = ch.codePointAt(0);
    if (!IS_ARMENIAN(cp)) continue;
    used.add(cp);
    if (!seenIn.has(cp)) seenIn.set(cp, relative(ROOT, file));
  }
}

if (used.size === 0) {
  console.log("No Armenian text in the source. Nothing to subset.");
  process.exit(0);
}

const codepoints = [...used].sort((a, b) => a - b);
const unicodes = codepoints.map((c) => `U+${c.toString(16).toUpperCase().padStart(4, "0")}`);

console.log(`Armenian characters in the source: ${codepoints.length}`);
for (const cp of codepoints) {
  console.log(
    `  ${String.fromCodePoint(cp)}  U+${cp.toString(16).toUpperCase().padStart(4, "0")}  first seen in ${seenIn.get(cp)}`,
  );
}

/* ---- 2. Find the Armenian font files from the generated stylesheet ---- */

let css = await readFile(CSS, "utf8");
const armenianFiles = new Set();

for (const m of css.matchAll(/\/\*\s*armenian\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)) {
  const url = /url\(([^)]+)\)/.exec(m[1] ?? "");
  if (url?.[1]) armenianFiles.add(url[1]);
}

if (armenianFiles.size === 0) {
  console.error("Found no Armenian @font-face blocks. Has fetch-fonts.mjs been run?");
  process.exit(1);
}

/* ---- 3. Subset each one ---- */

let before = 0;
let after = 0;

for (const url of armenianFiles) {
  const name = url.replace("/fonts/", "");
  const src = join(FONT_DIR, name);
  const outName = name.replace(/\.woff2$/, ".subset.woff2");
  const out = join(FONT_DIR, outName);

  before += (await stat(src)).size;

  await run("pyftsubset", [
    src,
    `--unicodes=${unicodes.join(",")}`,
    "--flavor=woff2",
    `--output-file=${out}`,
    "--layout-features=*",
    "--no-hinting",
    "--desubroutinize",
  ]);

  after += (await stat(out)).size;
  css = css.split(url).join(`/fonts/${outName}`);
  console.log(`  subset ${name} -> ${outName}`);
}

await writeFile(CSS, css);
await writeFile(
  MANIFEST,
  `${JSON.stringify({ note: "Generated by scripts/subset-fonts.mjs. The Armenian faces contain exactly these codepoints.", codepoints, characters: codepoints.map((c) => String.fromCodePoint(c)) }, null, 2)}\n`,
);

const saved = before - after;
console.log(
  `\nArmenian faces: ${(before / 1024).toFixed(1)} KB -> ${(after / 1024).toFixed(1)} KB ` +
    `(${(saved / 1024).toFixed(1)} KB saved on every page that shows Armenian text)`,
);
console.log("Wrote src/styles/armenian-subset.json so the HTML audit can check against it.");
